# 允许指定启动端口，默认在30000～50000随机选择一个可用端口
# port: 8081
# 最多记录历史房间号
max_history_room: 20
# 是否保存所有B站弹幕信息
save_all_bili_message: false
# 礼物色彩区分，price_top: 价格上界，自动寻找上一个下界，在此区间内的价格将使用该配置的颜色
price_properties:
  - price_top: 30
    bg_color: "#EDF5FF"
    bg_price_color: "#7497CD"
    bg_bottom_color: "#2A60B2"
    time: 60000
  - price_top: 50
    bg_color: "#DBFFFD"
    bg_price_color: "#7DA4BD"
    bg_bottom_color: "#427D9E"
    time: 120000
  - price_top: 100
    bg_color: "#FFF1C5"
    bg_price_color: "gold"
    bg_bottom_color: "#E2B52B"
    time: 300000
  - price_top: 500
    bg_color: "rgb(255,234,210)"
    bg_price_color: "rgb(255,234,210)"
    bg_bottom_color: "rgb(244,148,67)"
    time: 1800000
  - price_top: 1000
    bg_color: "rgb(255,231,228)"
    bg_price_color: "rgb(255,231,228)"
    bg_bottom_color: "rgb(229,77,77)"
    time: 3600000
  - price_top: 2000
    bg_color: "rgb(255,216,216)"
    bg_price_color: "rgb(255,216,216)"
    bg_bottom_color: "rgb(171,26,50)"
    time: 7200000