allowBuilds:
  '@alicloud/openapi-core': false
  bufferutil: false
  electron: true
  electron-winstaller: false
  esbuild: true
  highlight.js: false
  koa: true
  protobufjs: true
  utf-8-validate: false
blockExoticSubdeps: false
