export { default as FanMedal } from './components/FanMedal.vue'
export { default as GiftTag } from './components/GiftTag.vue'
export { default as GiftTagExpand } from './components/GiftTagExpand.vue'
export { default as SimilarCommentBadge } from './components/SimilarCommentBadge.vue'
export { default as GiftCard } from './components/GiftCard.vue'
export { default as GiftCardMini } from './components/GiftCardMini.vue'
export { GUARD_ICON_MAP, INTERACT_TYPE, COLORS, DEFAULT_AVATAR } from './service/const'
export { dateFormat } from './service/util'
